from .templates import (
    SYSTEM_PROMPT,
    STRUCTURE_OPTIMIZATION_PROMPT,
    QUALITY_EVALUATION_PROMPT,
    DEFAULT_REWRITE_PROMPT,
)

__all__ = [
    "SYSTEM_PROMPT",
    "STRUCTURE_OPTIMIZATION_PROMPT",
    "QUALITY_EVALUATION_PROMPT",
    "DEFAULT_REWRITE_PROMPT",
]
